# Generated by Django 5.1.3 on 2025-05-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_refactor', '0002_myupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUpload',
        ),
    ]
